// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectbox/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3200388878705800176),
    name: 'SpeakerProfileEntity',
    lastPropertyId: const obx_int.IdUid(6, 7695013108958009494),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6702059865944067861),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5345987891012576039),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4896971552185629249),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8451920050140837086),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7695013108958009494),
        name: 'nameKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 2947264841664275460),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'vectors',
        srcEntity: 'SpeakerVectorEntity',
        srcField: 'speaker',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1687012079620164052),
    name: 'SpeakerVectorEntity',
    lastPropertyId: const obx_int.IdUid(4, 1392604743333566476),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1656202792958724257),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3502700310038458288),
        name: 'speakerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3508564611448806414),
        relationField: 'speaker',
        relationTarget: 'SpeakerProfileEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6491080623561340642),
        name: 'embedding',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1392604743333566476),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8951984836733702572),
    name: 'TranscriptEntity',
    lastPropertyId: const obx_int.IdUid(7, 4106402967987977160),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5329062333556713166),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5216945440035634755),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8661120482805166472),
        name: 'model',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1266568489435921706),
        name: 'lang',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5345922877091796549),
        name: 'durationSec',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 799037357380662095),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4106402967987977160),
        name: 'audioPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'turns',
        srcEntity: 'TranscriptTurnEntity',
        srcField: 'transcript',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5744334615254339933),
    name: 'TranscriptTurnEntity',
    lastPropertyId: const obx_int.IdUid(6, 3684531645536754636),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7472799879046224792),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2899076633283858871),
        name: 'transcriptId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 197343125622883525),
        relationField: 'transcript',
        relationTarget: 'TranscriptEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 766513792105933622),
        name: 'speakerLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8930494030151307393),
        name: 'startSec',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2706587413564865508),
        name: 'endSec',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3684531645536754636),
        name: 'text',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7831950910300597404),
    name: 'TranscriptionJobEntity',
    lastPropertyId: const obx_int.IdUid(8, 8262934732911788997),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 36258057449499458),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 297764067916004067),
        name: 'wavPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4689568872317128278),
        name: 'translateToEnglish',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4683342057130356257),
        name: 'titleHint',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7581930211408447811),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8125824377358247077),
        name: 'transcriptId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3622792769210616683),
        name: 'error',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8262934732911788997),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 1274441994532829430),
    name: 'TranscriptChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(5, 3368783852519367829),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3420364209823227715),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8896178509220524013),
        name: 'transcriptId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 8733085736401595721),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6174848270693824875),
        name: 'isUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1273098618954495660),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3368783852519367829),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1361999600127992866),
    name: 'TranscriptSummaryEntity',
    lastPropertyId: const obx_int.IdUid(4, 5523908990864756026),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 789519095845763247),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8895227994930637095),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1364986997420540922),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5523908990864756026),
        name: 'transcriptId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 3039872481382531499),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 1361999600127992866),
    lastIndexId: const obx_int.IdUid(7, 3039872481382531499),
    lastRelationId: const obx_int.IdUid(1, 2617604582228853530),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [480077227493555476, 5443520686700661010],
    retiredPropertyUids: const [2821609119649167936],
    retiredRelationUids: const [2617604582228853530],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SpeakerProfileEntity: obx_int.EntityDefinition<SpeakerProfileEntity>(
      model: _entities[0],
      toOneRelations: (SpeakerProfileEntity object) => [],
      toManyRelations: (SpeakerProfileEntity object) => {
        obx_int.RelInfo<SpeakerVectorEntity>.toOneBacklink(
          2,
          object.id,
          (SpeakerVectorEntity srcObject) => srcObject.speaker,
        ): object.vectors,
      },
      getId: (SpeakerProfileEntity object) => object.id,
      setId: (SpeakerProfileEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SpeakerProfileEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final nameKeyOffset = fbb.writeString(object.nameKey);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(5, nameKeyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = SpeakerProfileEntity(
          id: idParam,
          name: nameParam,
          nameKey: nameKeyParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<SpeakerProfileEntity>(
          object.vectors,
          store,
          obx_int.RelInfo<SpeakerVectorEntity>.toOneBacklink(
            2,
            object.id,
            (SpeakerVectorEntity srcObject) => srcObject.speaker,
          ),
        );
        return object;
      },
    ),
    SpeakerVectorEntity: obx_int.EntityDefinition<SpeakerVectorEntity>(
      model: _entities[1],
      toOneRelations: (SpeakerVectorEntity object) => [object.speaker],
      toManyRelations: (SpeakerVectorEntity object) => {},
      getId: (SpeakerVectorEntity object) => object.id,
      setId: (SpeakerVectorEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SpeakerVectorEntity object, fb.Builder fbb) {
        final embeddingOffset = fbb.writeListInt8(object.embedding);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.speaker.targetId);
        fbb.addOffset(2, embeddingOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final embeddingParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGet(buffer, rootOffset, 8, Uint8List(0))
                as Uint8List;
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = SpeakerVectorEntity(
          id: idParam,
          embedding: embeddingParam,
          createdAt: createdAtParam,
        );
        object.speaker.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.speaker.attach(store);
        return object;
      },
    ),
    TranscriptEntity: obx_int.EntityDefinition<TranscriptEntity>(
      model: _entities[2],
      toOneRelations: (TranscriptEntity object) => [],
      toManyRelations: (TranscriptEntity object) => {
        obx_int.RelInfo<TranscriptTurnEntity>.toOneBacklink(
          2,
          object.id,
          (TranscriptTurnEntity srcObject) => srcObject.transcript,
        ): object.turns,
      },
      getId: (TranscriptEntity object) => object.id,
      setId: (TranscriptEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptEntity object, fb.Builder fbb) {
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final modelOffset = fbb.writeString(object.model);
        final langOffset = fbb.writeString(object.lang);
        final audioPathOffset = object.audioPath == null
            ? null
            : fbb.writeString(object.audioPath!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, modelOffset);
        fbb.addOffset(3, langOffset);
        fbb.addFloat64(4, object.durationSec);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(6, audioPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final modelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final langParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final audioPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final durationSecParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = TranscriptEntity(
          id: idParam,
          title: titleParam,
          model: modelParam,
          lang: langParam,
          audioPath: audioPathParam,
          durationSec: durationSecParam,
          createdAt: createdAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<TranscriptEntity>(
          object.turns,
          store,
          obx_int.RelInfo<TranscriptTurnEntity>.toOneBacklink(
            2,
            object.id,
            (TranscriptTurnEntity srcObject) => srcObject.transcript,
          ),
        );
        return object;
      },
    ),
    TranscriptTurnEntity: obx_int.EntityDefinition<TranscriptTurnEntity>(
      model: _entities[3],
      toOneRelations: (TranscriptTurnEntity object) => [object.transcript],
      toManyRelations: (TranscriptTurnEntity object) => {},
      getId: (TranscriptTurnEntity object) => object.id,
      setId: (TranscriptTurnEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptTurnEntity object, fb.Builder fbb) {
        final speakerLabelOffset = fbb.writeString(object.speakerLabel);
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.transcript.targetId);
        fbb.addOffset(2, speakerLabelOffset);
        fbb.addFloat64(3, object.startSec);
        fbb.addFloat64(4, object.endSec);
        fbb.addOffset(5, textOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final speakerLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startSecParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final endSecParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = TranscriptTurnEntity(
          id: idParam,
          speakerLabel: speakerLabelParam,
          startSec: startSecParam,
          endSec: endSecParam,
          text: textParam,
        );
        object.transcript.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.transcript.attach(store);
        return object;
      },
    ),
    TranscriptionJobEntity: obx_int.EntityDefinition<TranscriptionJobEntity>(
      model: _entities[4],
      toOneRelations: (TranscriptionJobEntity object) => [],
      toManyRelations: (TranscriptionJobEntity object) => {},
      getId: (TranscriptionJobEntity object) => object.id,
      setId: (TranscriptionJobEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptionJobEntity object, fb.Builder fbb) {
        final wavPathOffset = fbb.writeString(object.wavPath);
        final titleHintOffset = object.titleHint == null
            ? null
            : fbb.writeString(object.titleHint!);
        final statusOffset = fbb.writeString(object.status);
        final errorOffset = object.error == null
            ? null
            : fbb.writeString(object.error!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, wavPathOffset);
        fbb.addBool(2, object.translateToEnglish);
        fbb.addOffset(3, titleHintOffset);
        fbb.addOffset(4, statusOffset);
        fbb.addInt64(5, object.transcriptId);
        fbb.addOffset(6, errorOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final wavPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final translateToEnglishParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final transcriptIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final titleHintParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final errorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = TranscriptionJobEntity(
          id: idParam,
          wavPath: wavPathParam,
          translateToEnglish: translateToEnglishParam,
          transcriptId: transcriptIdParam,
          titleHint: titleHintParam,
          status: statusParam,
          error: errorParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    TranscriptChatMessageEntity:
        obx_int.EntityDefinition<TranscriptChatMessageEntity>(
          model: _entities[5],
          toOneRelations: (TranscriptChatMessageEntity object) => [],
          toManyRelations: (TranscriptChatMessageEntity object) => {},
          getId: (TranscriptChatMessageEntity object) => object.id,
          setId: (TranscriptChatMessageEntity object, int id) {
            object.id = id;
          },
          objectToFB: (TranscriptChatMessageEntity object, fb.Builder fbb) {
            final textOffset = fbb.writeString(object.text);
            fbb.startTable(6);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.transcriptId);
            fbb.addBool(2, object.isUser);
            fbb.addOffset(3, textOffset);
            fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final transcriptIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              6,
              0,
            );
            final isUserParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              8,
              false,
            );
            final textParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
            );
            final object = TranscriptChatMessageEntity(
              id: idParam,
              transcriptId: transcriptIdParam,
              isUser: isUserParam,
              text: textParam,
              createdAt: createdAtParam,
            );

            return object;
          },
        ),
    TranscriptSummaryEntity: obx_int.EntityDefinition<TranscriptSummaryEntity>(
      model: _entities[6],
      toOneRelations: (TranscriptSummaryEntity object) => [],
      toManyRelations: (TranscriptSummaryEntity object) => {},
      getId: (TranscriptSummaryEntity object) => object.id,
      setId: (TranscriptSummaryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptSummaryEntity object, fb.Builder fbb) {
        final summaryOffset = fbb.writeString(object.summary);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, summaryOffset);
        fbb.addInt64(2, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.transcriptId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final transcriptIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = TranscriptSummaryEntity(
          id: idParam,
          transcriptId: transcriptIdParam,
          summary: summaryParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SpeakerProfileEntity] entity fields to define ObjectBox queries.
class SpeakerProfileEntity_ {
  /// See [SpeakerProfileEntity.id].
  static final id = obx.QueryIntegerProperty<SpeakerProfileEntity>(
    _entities[0].properties[0],
  );

  /// See [SpeakerProfileEntity.name].
  static final name = obx.QueryStringProperty<SpeakerProfileEntity>(
    _entities[0].properties[1],
  );

  /// See [SpeakerProfileEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<SpeakerProfileEntity>(
    _entities[0].properties[2],
  );

  /// See [SpeakerProfileEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<SpeakerProfileEntity>(
    _entities[0].properties[3],
  );

  /// See [SpeakerProfileEntity.nameKey].
  static final nameKey = obx.QueryStringProperty<SpeakerProfileEntity>(
    _entities[0].properties[4],
  );

  /// see [SpeakerProfileEntity.vectors]
  static final vectors =
      obx.QueryBacklinkToMany<SpeakerVectorEntity, SpeakerProfileEntity>(
        SpeakerVectorEntity_.speaker,
      );
}

/// [SpeakerVectorEntity] entity fields to define ObjectBox queries.
class SpeakerVectorEntity_ {
  /// See [SpeakerVectorEntity.id].
  static final id = obx.QueryIntegerProperty<SpeakerVectorEntity>(
    _entities[1].properties[0],
  );

  /// See [SpeakerVectorEntity.speaker].
  static final speaker =
      obx.QueryRelationToOne<SpeakerVectorEntity, SpeakerProfileEntity>(
        _entities[1].properties[1],
      );

  /// See [SpeakerVectorEntity.embedding].
  static final embedding = obx.QueryByteVectorProperty<SpeakerVectorEntity>(
    _entities[1].properties[2],
  );

  /// See [SpeakerVectorEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<SpeakerVectorEntity>(
    _entities[1].properties[3],
  );
}

/// [TranscriptEntity] entity fields to define ObjectBox queries.
class TranscriptEntity_ {
  /// See [TranscriptEntity.id].
  static final id = obx.QueryIntegerProperty<TranscriptEntity>(
    _entities[2].properties[0],
  );

  /// See [TranscriptEntity.title].
  static final title = obx.QueryStringProperty<TranscriptEntity>(
    _entities[2].properties[1],
  );

  /// See [TranscriptEntity.model].
  static final model = obx.QueryStringProperty<TranscriptEntity>(
    _entities[2].properties[2],
  );

  /// See [TranscriptEntity.lang].
  static final lang = obx.QueryStringProperty<TranscriptEntity>(
    _entities[2].properties[3],
  );

  /// See [TranscriptEntity.durationSec].
  static final durationSec = obx.QueryDoubleProperty<TranscriptEntity>(
    _entities[2].properties[4],
  );

  /// See [TranscriptEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TranscriptEntity>(
    _entities[2].properties[5],
  );

  /// See [TranscriptEntity.audioPath].
  static final audioPath = obx.QueryStringProperty<TranscriptEntity>(
    _entities[2].properties[6],
  );

  /// see [TranscriptEntity.turns]
  static final turns =
      obx.QueryBacklinkToMany<TranscriptTurnEntity, TranscriptEntity>(
        TranscriptTurnEntity_.transcript,
      );
}

/// [TranscriptTurnEntity] entity fields to define ObjectBox queries.
class TranscriptTurnEntity_ {
  /// See [TranscriptTurnEntity.id].
  static final id = obx.QueryIntegerProperty<TranscriptTurnEntity>(
    _entities[3].properties[0],
  );

  /// See [TranscriptTurnEntity.transcript].
  static final transcript =
      obx.QueryRelationToOne<TranscriptTurnEntity, TranscriptEntity>(
        _entities[3].properties[1],
      );

  /// See [TranscriptTurnEntity.speakerLabel].
  static final speakerLabel = obx.QueryStringProperty<TranscriptTurnEntity>(
    _entities[3].properties[2],
  );

  /// See [TranscriptTurnEntity.startSec].
  static final startSec = obx.QueryDoubleProperty<TranscriptTurnEntity>(
    _entities[3].properties[3],
  );

  /// See [TranscriptTurnEntity.endSec].
  static final endSec = obx.QueryDoubleProperty<TranscriptTurnEntity>(
    _entities[3].properties[4],
  );

  /// See [TranscriptTurnEntity.text].
  static final text = obx.QueryStringProperty<TranscriptTurnEntity>(
    _entities[3].properties[5],
  );
}

/// [TranscriptionJobEntity] entity fields to define ObjectBox queries.
class TranscriptionJobEntity_ {
  /// See [TranscriptionJobEntity.id].
  static final id = obx.QueryIntegerProperty<TranscriptionJobEntity>(
    _entities[4].properties[0],
  );

  /// See [TranscriptionJobEntity.wavPath].
  static final wavPath = obx.QueryStringProperty<TranscriptionJobEntity>(
    _entities[4].properties[1],
  );

  /// See [TranscriptionJobEntity.translateToEnglish].
  static final translateToEnglish =
      obx.QueryBooleanProperty<TranscriptionJobEntity>(
        _entities[4].properties[2],
      );

  /// See [TranscriptionJobEntity.titleHint].
  static final titleHint = obx.QueryStringProperty<TranscriptionJobEntity>(
    _entities[4].properties[3],
  );

  /// See [TranscriptionJobEntity.status].
  static final status = obx.QueryStringProperty<TranscriptionJobEntity>(
    _entities[4].properties[4],
  );

  /// See [TranscriptionJobEntity.transcriptId].
  static final transcriptId = obx.QueryIntegerProperty<TranscriptionJobEntity>(
    _entities[4].properties[5],
  );

  /// See [TranscriptionJobEntity.error].
  static final error = obx.QueryStringProperty<TranscriptionJobEntity>(
    _entities[4].properties[6],
  );

  /// See [TranscriptionJobEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TranscriptionJobEntity>(
    _entities[4].properties[7],
  );
}

/// [TranscriptChatMessageEntity] entity fields to define ObjectBox queries.
class TranscriptChatMessageEntity_ {
  /// See [TranscriptChatMessageEntity.id].
  static final id = obx.QueryIntegerProperty<TranscriptChatMessageEntity>(
    _entities[5].properties[0],
  );

  /// See [TranscriptChatMessageEntity.transcriptId].
  static final transcriptId =
      obx.QueryIntegerProperty<TranscriptChatMessageEntity>(
        _entities[5].properties[1],
      );

  /// See [TranscriptChatMessageEntity.isUser].
  static final isUser = obx.QueryBooleanProperty<TranscriptChatMessageEntity>(
    _entities[5].properties[2],
  );

  /// See [TranscriptChatMessageEntity.text].
  static final text = obx.QueryStringProperty<TranscriptChatMessageEntity>(
    _entities[5].properties[3],
  );

  /// See [TranscriptChatMessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TranscriptChatMessageEntity>(
    _entities[5].properties[4],
  );
}

/// [TranscriptSummaryEntity] entity fields to define ObjectBox queries.
class TranscriptSummaryEntity_ {
  /// See [TranscriptSummaryEntity.id].
  static final id = obx.QueryIntegerProperty<TranscriptSummaryEntity>(
    _entities[6].properties[0],
  );

  /// See [TranscriptSummaryEntity.summary].
  static final summary = obx.QueryStringProperty<TranscriptSummaryEntity>(
    _entities[6].properties[1],
  );

  /// See [TranscriptSummaryEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TranscriptSummaryEntity>(
    _entities[6].properties[2],
  );

  /// See [TranscriptSummaryEntity.transcriptId].
  static final transcriptId = obx.QueryIntegerProperty<TranscriptSummaryEntity>(
    _entities[6].properties[3],
  );
}
